[build]
	command = "# no build command"
	functions = "netlify/functions"
	publish = "public"

[functions]
        node_bundler = "esbuild"
[[redirects]]
  from = "/api"
  to = "https://nsfestival.fr/wp-json/wp/v2/media"
  status = 200
  force = true
  headers = {X-From = "Netlify"}